# Generated by Django 2.0.7 on 2018-07-24 20:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('PEOPLE', 'People'), ('NATURE', 'Nature'), ('CITY_LIFE', 'City Life'), ('LOVE', 'Love'), ('SPORTS', 'Sports'), ('FAMILY', 'Family'), ('General', 'General')], default='General', max_length=12)),
                ('location', models.TextField(blank=True)),
                ('up_votes', models.IntegerField(default=0)),
                ('down_votes', models.IntegerField(default=0)),
                ('view_count', models.IntegerField(default=0)),
                ('photo_url', models.ImageField(upload_to='photos/%Y/%m/%d/%H/%M/%S')),
                ('date_last_modified', models.DateTimeField(auto_now=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
    ]
